name: CI — Validate Content & Tests

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install (dev)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Export schemas (check docs up to date)
        run: |
          python -m dndrpg.tools.validate export-schemas --out .schemas_tmp
          if ! diff -qr .schemas_tmp docs/schemas ; then
            echo "::warning::Schema docs differ from generated (update docs/schemas if intended)."
          fi

      - name: Validate content (strict)
        run: dndrpg-tools validate-content --strict

      - name: Run tests
        run: pytest -q